"use client";

import { useEffect, useState } from "react";
import { apiFetch } from "@/lib/api-client";

type PlanItem = { id: string; title: string; item_type: string; starts_at: string | null; ends_at: string | null; is_manual: boolean };
type Plan = { id: string; plan_date: string; generated_by_rules: boolean; items: PlanItem[] };

export default function WorkPlanPage() {
  const [plan, setPlan] = useState<Plan | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { apiFetch<PlanItem[]>("/intelligence/daily-plan").then((items) => setPlan({ id: "", plan_date: new Date().toISOString().slice(0, 10), generated_by_rules: true, items })).catch(() => setError("Unable to generate today's work plan.")); }, []);
  return <section><h1 className="text-3xl font-bold">Smart daily work plan</h1><p className="mt-2 text-slate-600">A transparent, deterministic plan based on deadlines, priorities, meetings, effort, and availability. You can edit it manually.</p>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<div className="mt-6 rounded-xl bg-white shadow-sm"><div className="border-b px-5 py-4"><p className="font-semibold">{plan?.plan_date || "Today"}</p><p className="mt-1 text-xs text-slate-500">{plan?.generated_by_rules ? "Generated by deterministic rules" : ""}</p></div>{plan?.items?.length ? plan.items.map((item) => <div key={item.id} className="flex items-center justify-between border-b px-5 py-4"><div><p className="font-medium">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.item_type} {item.starts_at ? `· ${new Date(item.starts_at).toLocaleTimeString()}` : ""}</p></div>{item.is_manual && <span className="text-xs text-blue-600">Edited</span>}</div>) : <p className="px-5 py-8 text-sm text-slate-500">No planned items for today.</p>}</div></section>;
}
