"""project, task and meeting workflows
Revision ID: 003_project_task_meeting_workflows
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "003_project_task_meeting_workflows"
down_revision = "002_attendance_leave_calendar"
branch_labels = None
depends_on = None
uuid = postgresql.UUID(as_uuid=True)

def upgrade():
    op.create_table("projects", sa.Column("id", uuid, primary_key=True), sa.Column("company_id", uuid, sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("owner_id", uuid, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("team_id", uuid, sa.ForeignKey("teams.id", ondelete="SET NULL")), sa.Column("name", sa.String(200), nullable=False), sa.Column("description", sa.Text), sa.Column("status", sa.String(30), nullable=False, server_default="PLANNING"), sa.Column("priority", sa.String(20), nullable=False, server_default="MEDIUM"), sa.Column("start_date", sa.DateTime(timezone=True)), sa.Column("target_date", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("project_members", sa.Column("id", uuid, primary_key=True), sa.Column("project_id", uuid, sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", uuid, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("is_lead", sa.Boolean, nullable=False, server_default=sa.false()), sa.UniqueConstraint("project_id", "user_id"))
    op.create_table("tasks", sa.Column("id", uuid, primary_key=True), sa.Column("project_id", uuid, sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("creator_id", uuid, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("assignee_id", uuid, sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("title", sa.String(300), nullable=False), sa.Column("description", sa.Text), sa.Column("status", sa.String(30), nullable=False, server_default="TODO"), sa.Column("priority", sa.String(20), nullable=False, server_default="MEDIUM"), sa.Column("progress", sa.Integer, nullable=False, server_default="0"), sa.Column("kanban_order", sa.Integer, nullable=False, server_default="0"), sa.Column("due_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("task_comments", sa.Column("id", uuid, primary_key=True), sa.Column("task_id", uuid, sa.ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False), sa.Column("author_id", uuid, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("body", sa.Text, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("task_assignees", sa.Column("id", uuid, primary_key=True), sa.Column("task_id", uuid, sa.ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", uuid, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False))
    op.create_table("task_history", sa.Column("id", uuid, primary_key=True), sa.Column("task_id", uuid, sa.ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False), sa.Column("actor_id", uuid, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("from_status", sa.String(30)), sa.Column("to_status", sa.String(30), nullable=False), sa.Column("note", sa.Text), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("meetings", sa.Column("id", uuid, primary_key=True), sa.Column("company_id", uuid, sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("organizer_id", uuid, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("project_id", uuid, sa.ForeignKey("projects.id", ondelete="SET NULL")), sa.Column("title", sa.String(200), nullable=False), sa.Column("description", sa.Text), sa.Column("agenda", sa.Text), sa.Column("location", sa.String(300)), sa.Column("meeting_link", sa.String(500)), sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False), sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="scheduled"), sa.Column("calendar_event_id", uuid, sa.ForeignKey("calendar_events.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("meeting_participants", sa.Column("id", uuid, primary_key=True), sa.Column("meeting_id", uuid, sa.ForeignKey("meetings.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", uuid, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("can_edit", sa.Boolean, nullable=False, server_default=sa.false()), sa.UniqueConstraint("meeting_id", "user_id"))
    op.create_table("meeting_moms", sa.Column("id", uuid, primary_key=True), sa.Column("meeting_id", uuid, sa.ForeignKey("meetings.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("author_id", uuid, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("notes", sa.Text, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("action_item_suggestions", sa.Column("id", uuid, primary_key=True), sa.Column("meeting_id", uuid, sa.ForeignKey("meetings.id", ondelete="CASCADE"), nullable=False), sa.Column("suggested_by_id", uuid, sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("title", sa.String(300), nullable=False), sa.Column("description", sa.Text), sa.Column("assignee_id", uuid, sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("status", sa.String(20), nullable=False, server_default="pending"), sa.Column("approved_task_id", uuid, sa.ForeignKey("tasks.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))

def downgrade():
    for t in ("action_item_suggestions", "meeting_moms", "meeting_participants", "meetings", "task_history", "task_assignees", "task_comments", "tasks", "project_members", "projects"):
        op.drop_table(t)
